name: firebasedb-reservation-system
services:
  - name: reservation-backend
    source:
      type: git
      url: https://github.com/your-username/firebasedb.git
      branch: main
    build:
      type: nodejs
      version: 18
      buildCommand: npm install
      startCommand: npm start
    env:
      - name: NODE_ENV
        value: production
      - name: PORT
        value: 3000
      - name: DATABASE_PATH
        value: /app/database/reservations.db
      - name: FIREBASE_PROJECT_ID
        value: your-firebase-project-id
      - name: FIREBASE_PRIVATE_KEY
        value: your-firebase-private-key
      - name: FIREBASE_CLIENT_EMAIL
        value: your-firebase-client-email
    resources:
      cpu: 0.5
      memory: 512Mi
    ports:
      - port: 3000
        protocol: http
    healthCheck:
      path: /health
      port: 3000
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3 